
import React, { useState } from 'react';
import { BusinessPlan, GeneratedFile } from '../types';
import { 
  TrendingUp, 
  Target, 
  Globe, 
  DollarSign, 
  Code2, 
  GitBranch,
  MousePointerClick,
  Zap,
  Copy,
  Terminal,
  FileCode,
  Check,
  Map,
  Sword,
  Skull,
  SearchX,
  Download,
  Package
} from 'lucide-react';
import JSZip from 'jszip';
import FileSaver from 'file-saver';

interface DashboardProps {
  plan: BusinessPlan;
  onReset: () => void;
}

const SectionHeader: React.FC<{ icon: React.ReactNode; title: string; subtitle?: string }> = ({ icon, title, subtitle }) => (
  <div className="flex items-start gap-4 mb-6 border-b border-slate-800 pb-4">
    <div className="p-3 bg-slate-800 rounded-lg text-emerald-400 shadow-lg shadow-emerald-900/20">
      {icon}
    </div>
    <div>
      <h2 className="text-2xl font-bold text-white">{title}</h2>
      {subtitle && <p className="text-slate-400 text-sm mt-1">{subtitle}</p>}
    </div>
  </div>
);

const CodeBlock: React.FC<{ file: GeneratedFile }> = ({ file }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(file.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-slate-950 rounded-lg border border-slate-800 overflow-hidden my-4">
      <div className="flex justify-between items-center px-4 py-2 bg-slate-900 border-b border-slate-800">
        <div className="flex items-center gap-2">
          <FileCode className="w-4 h-4 text-emerald-500" />
          <span className="font-mono text-xs text-slate-300">{file.path}</span>
        </div>
        <button 
          onClick={handleCopy}
          className="flex items-center gap-1 text-xs text-slate-400 hover:text-white transition-colors"
        >
          {copied ? <Check className="w-3 h-3 text-emerald-500" /> : <Copy className="w-3 h-3" />}
          {copied ? 'Copied' : 'Copy'}
        </button>
      </div>
      <pre className="p-4 overflow-x-auto text-xs font-mono text-slate-300 leading-relaxed max-h-96 overflow-y-auto custom-scrollbar">
        <code>{file.content}</code>
      </pre>
    </div>
  );
};

export const Dashboard: React.FC<DashboardProps> = ({ plan, onReset }) => {
  const [activeTab, setActiveTab] = useState<'strategy' | 'code'>('strategy');
  const [isZipping, setIsZipping] = useState(false);

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 2,
    }).format(amount);
  };

  const handleDownloadZip = async () => {
    setIsZipping(true);
    try {
      const zip = new JSZip();
      const projectName = `jack-industries-${plan.niche.toLowerCase().replace(/\s+/g, '-')}-${plan.location.toLowerCase().replace(/\s+/g, '-')}`;
      const folder = zip.folder(projectName);

      if (folder && plan.siteAssets) {
        plan.siteAssets.forEach(file => {
          folder.file(file.path, file.content);
        });

        // Generate README
        const readme = `# ${plan.niche} in ${plan.location}\n\nGenerated by Rank & Rent Factory.\n\n## Quick Start\n\n1. \`npm install\`\n2. \`npm run dev\`\n\n## Stack\n- Astro\n- React\n- Tailwind`;
        folder.file("README.md", readme);

        const content = await zip.generateAsync({ type: "blob" });
        
        // Handle FileSaver export differences across environments
        const save = (FileSaver as any).saveAs || FileSaver;
        save(content, `${projectName}.zip`);
      }
    } catch (error) {
      console.error("Failed to zip", error);
      alert("Failed to generate ZIP file.");
    } finally {
      setIsZipping(false);
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 py-8 animate-fade-in">
      {/* Header Navigation */}
      <div className="flex flex-col md:flex-row justify-between items-center mb-8 gap-4">
        <div>
          <h1 className="text-xl font-bold text-white flex items-center gap-2">
            <span className="w-2 h-8 bg-emerald-500 rounded-sm inline-block"></span>
             FACTORY: {plan.niche.toUpperCase()} IN {plan.location.toUpperCase()}
          </h1>
        </div>
        
        <div className="flex items-center gap-4">
          <div className="flex bg-slate-900 p-1 rounded-lg border border-slate-800">
            <button 
              onClick={() => setActiveTab('strategy')}
              className={`px-4 py-2 rounded-md text-sm font-bold transition-all ${activeTab === 'strategy' ? 'bg-emerald-600 text-white shadow-lg' : 'text-slate-400 hover:text-white'}`}
            >
              Strategy
            </button>
            <button 
              onClick={() => setActiveTab('code')}
              className={`px-4 py-2 rounded-md text-sm font-bold transition-all flex items-center gap-2 ${activeTab === 'code' ? 'bg-emerald-600 text-white shadow-lg' : 'text-slate-400 hover:text-white'}`}
            >
              <Code2 className="w-4 h-4" />
              Source Code
            </button>
          </div>
        </div>

        <button 
          onClick={onReset}
          className="text-sm text-slate-400 hover:text-white underline decoration-emerald-500/50 hover:decoration-emerald-500 transition-all"
        >
          New Search
        </button>
      </div>

      {/* Executive Summary */}
      <div className="bg-gradient-to-br from-slate-900 to-slate-850 border border-emerald-900/30 p-6 rounded-xl mb-8 shadow-2xl relative overflow-hidden">
        <div className="absolute top-0 right-0 p-4 opacity-10">
          <Target size={120} />
        </div>
        <h3 className="text-emerald-400 font-mono text-sm mb-2 tracking-wider uppercase">Strategist's Note</h3>
        <p className="text-slate-200 text-lg leading-relaxed font-serif italic border-l-4 border-emerald-500 pl-4">
          "{plan.executiveSummary}"
        </p>
      </div>

      {activeTab === 'strategy' ? (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          
          {/* Left Column: Strategy & Domain (4 cols) */}
          <div className="lg:col-span-4 space-y-8">
            
            {/* Domain Strategy */}
            <section className="bg-slate-900 border border-slate-800 rounded-xl p-6">
              <SectionHeader 
                icon={<Globe className="w-6 h-6" />} 
                title="The Asset" 
                subtitle="Domain Name Strategy" 
              />
              <div className="bg-slate-950 p-4 rounded-lg border border-slate-800 mb-4">
                <div className="text-xs text-slate-500 uppercase mb-1">Primary Target</div>
                <div className="text-2xl font-mono font-bold text-emerald-400 break-all">
                  {plan.domainStrategy.selectedDomain}
                </div>
                <div className="mt-2 inline-flex items-center px-2 py-1 rounded bg-emerald-500/10 text-emerald-400 text-xs font-bold">
                  {plan.domainStrategy.domainType}
                </div>
              </div>
              <p className="text-slate-400 text-sm mb-4">{plan.domainStrategy.rationale}</p>
            </section>

            {/* Competitor Recon */}
            <section className="bg-slate-900 border border-slate-800 rounded-xl p-6">
               <SectionHeader 
                icon={<Sword className="w-6 h-6" />} 
                title="Competitor Recon" 
                subtitle="Weakness Analysis" 
              />
              <div className="space-y-4">
                {plan.competitorAnalysis.map((comp, i) => (
                  <div key={i} className="bg-slate-950 p-3 rounded-lg border border-slate-800">
                    <div className="flex items-center gap-2 mb-1">
                      <Skull className="w-3 h-3 text-rose-500" />
                      <h4 className="text-slate-200 text-sm font-bold">{comp.name}</h4>
                    </div>
                    <p className="text-xs text-rose-400 mb-2">⚠ "{comp.weakness}"</p>
                    <div className="flex flex-wrap gap-1">
                      {comp.contentGap.slice(0, 2).map((gap, j) => (
                         <span key={j} className="px-2 py-0.5 bg-slate-800 text-slate-400 text-[10px] rounded">
                           Missed: {gap}
                         </span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </section>

          </div>

          {/* Right Column: Data & Financials (8 cols) */}
          <div className="lg:col-span-8 space-y-8">
            
            {/* Profit Projection Cards */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="bg-slate-900 p-4 rounded-xl border border-slate-800 text-center">
                <div className="text-xs text-slate-500 uppercase mb-1">Total Leads</div>
                <div className="text-2xl font-bold text-white">{plan.profitProjection.leadsCount}</div>
              </div>
              <div className="bg-slate-900 p-4 rounded-xl border border-slate-800 text-center">
                <div className="text-xs text-slate-500 uppercase mb-1">Est. Ad Spend</div>
                <div className="text-2xl font-bold text-rose-400">-{formatCurrency(plan.profitProjection.estimatedAdSpend)}</div>
              </div>
               <div className="bg-slate-900 p-4 rounded-xl border border-slate-800 text-center">
                <div className="text-xs text-slate-500 uppercase mb-1">Revenue</div>
                <div className="text-2xl font-bold text-emerald-400">{formatCurrency(plan.profitProjection.totalPotentialRevenue)}</div>
              </div>
               <div className="bg-slate-900 p-4 rounded-xl border border-slate-800 text-center ring-1 ring-emerald-500/50">
                <div className="text-xs text-emerald-500 font-bold uppercase mb-1">Net Profit</div>
                <div className="text-2xl font-bold text-emerald-400">{formatCurrency(plan.profitProjection.netProfit)}</div>
              </div>
            </div>

            {/* Geo Grid Strategy */}
             <section className="bg-slate-900 border border-slate-800 rounded-xl p-6">
               <SectionHeader 
                  icon={<Map className="w-6 h-6" />} 
                  title="Geo-Grid Attack Plan" 
                  subtitle="Hyper-Local Neighborhood Targeting (Programmatic)" 
                />
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                  {plan.geoGridStrategy.map((point, i) => (
                    <div key={i} className="bg-slate-950 p-3 rounded border border-slate-800 flex flex-col justify-between group hover:border-emerald-500/50 transition-colors">
                      <span className="text-white font-bold text-sm truncate" title={point.name}>{point.name}</span>
                      <div className="flex justify-between items-end mt-2">
                        <span className="text-[10px] text-slate-500 uppercase">{point.type}</span>
                        <span className={`text-[10px] font-bold ${point.targetValue === 'High' ? 'text-emerald-400' : 'text-yellow-400'}`}>
                          {point.targetValue} VAL
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
                <div className="mt-4 text-xs text-slate-500 italic flex items-center gap-2">
                   <SearchX className="w-3 h-3" />
                   These locations will be auto-generated in 'src/data/siteData.ts'
                </div>
            </section>

            {/* Lead Wizard (Funnel) */}
            <section className="bg-slate-900 border border-slate-800 rounded-xl p-6 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/5 rounded-full blur-3xl -mr-16 -mt-16 pointer-events-none"></div>
               <SectionHeader 
                  icon={<MousePointerClick className="w-6 h-6" />} 
                  title="The Lead Wizard" 
                  subtitle="Micro-Commitment Funnel (ProntoPro Style)" 
                />
                
                <p className="text-slate-400 text-sm mb-6 max-w-2xl">
                  {plan.leadFunnel.strategy}
                </p>

                <div className="space-y-0 relative">
                  <div className="absolute left-4 top-4 bottom-4 w-0.5 bg-slate-800"></div>
                  {plan.leadFunnel.questions.map((q, i) => (
                    <div key={i} className="relative pl-12 pb-6 last:pb-0 group">
                      <div className="absolute left-0 top-0 w-8 h-8 bg-slate-800 border border-emerald-900/50 rounded-full flex items-center justify-center text-emerald-500 font-bold text-sm z-10 group-hover:border-emerald-500 transition-colors shadow-lg shadow-black">
                        {i + 1}
                      </div>
                      <div className="bg-slate-950/50 border border-slate-800 p-4 rounded-lg hover:border-slate-700 transition-all">
                        <h4 className="text-white font-semibold text-lg mb-3">"{q.question}"</h4>
                        <div className="flex flex-wrap gap-2 mb-3">
                          {q.options.map((opt, j) => (
                            <span key={j} className="px-3 py-1 bg-slate-800 text-slate-300 text-xs rounded-md border border-slate-700">
                              {opt}
                            </span>
                          ))}
                        </div>
                        <div className="text-xs text-slate-500 italic border-l-2 border-slate-800 pl-2">
                          Why: {q.rationale}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
            </section>

            {/* Site Architecture */}
            <section className="bg-slate-900 border border-slate-800 rounded-xl p-6">
               <SectionHeader 
                  icon={<GitBranch className="w-6 h-6" />} 
                  title="Silo Architecture" 
                  subtitle="Programmatic SEO Structure" 
                />
                <div className="grid gap-4 md:grid-cols-2">
                  {plan.websiteStructure.serviceSilos.map((page, i) => (
                    <div key={i} className="bg-slate-950 p-4 rounded-lg border border-slate-800 hover:border-emerald-500/30 transition-colors">
                      <div className="flex items-center gap-2 mb-2">
                        <Zap className="w-4 h-4 text-emerald-500" />
                        <span className="text-white font-bold text-sm">/{page.urlSlug}</span>
                      </div>
                      <div className="text-slate-300 text-sm mb-3">{page.pageTitle}</div>
                      <div className="text-xs text-slate-500 uppercase">Target: "{page.targetKeyword}"</div>
                    </div>
                  ))}
                </div>
            </section>

            {/* Keyword Data */}
            <section className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden">
               <div className="p-6 pb-0">
                <SectionHeader 
                  icon={<TrendingUp className="w-6 h-6" />} 
                  title="Money Keywords" 
                  subtitle="Google Ads & Organic Targets" 
                />
               </div>
               <div className="overflow-x-auto">
                 <table className="w-full text-left border-collapse">
                   <thead>
                     <tr className="bg-slate-950 text-slate-400 text-xs uppercase tracking-wider">
                       <th className="p-4 font-medium">Keyword</th>
                       <th className="p-4 font-medium text-right">Vol</th>
                       <th className="p-4 font-medium text-center">Comp</th>
                       <th className="p-4 font-medium text-right">CPC</th>
                     </tr>
                   </thead>
                   <tbody className="text-sm divide-y divide-slate-800">
                     {plan.keywords.slice(0, 5).map((kw, idx) => (
                       <tr key={idx} className="hover:bg-slate-800/50 transition-colors">
                         <td className="p-4 font-medium text-white">{kw.keyword}</td>
                         <td className="p-4 text-right text-slate-300">{kw.avgMonthlySearches}</td>
                         <td className="p-4 text-center">
                           <span className={`px-2 py-1 rounded text-[10px] font-bold uppercase ${
                             kw.competition === 'High' ? 'bg-rose-500/20 text-rose-400' :
                             kw.competition === 'Medium' ? 'bg-yellow-500/20 text-yellow-400' :
                             'bg-emerald-500/20 text-emerald-400'
                           }`}>{kw.competition}</span>
                         </td>
                         <td className="p-4 text-right text-slate-400">{formatCurrency(kw.cpcHigh)}</td>
                       </tr>
                     ))}
                   </tbody>
                 </table>
               </div>
            </section>

          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-8 animate-fade-in">
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
             <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4">
               <SectionHeader 
                  icon={<Package className="w-6 h-6" />} 
                  title="Deployment Bundle" 
                  subtitle="Astro Project v4 (ProntoPro Style)" 
               />
               <button 
                onClick={handleDownloadZip}
                disabled={isZipping || !plan.siteAssets || plan.siteAssets.length === 0}
                className="bg-emerald-600 hover:bg-emerald-500 text-white font-bold py-3 px-6 rounded-lg flex items-center gap-2 transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-emerald-900/20"
               >
                 {isZipping ? (
                   <>Processing...</>
                 ) : (
                   <>
                     <Download className="w-5 h-5" />
                     Download Project (.ZIP)
                   </>
                 )}
               </button>
             </div>
             
             <div className="bg-slate-950/50 p-4 rounded-lg border border-emerald-900/30 mb-6">
                <h4 className="text-emerald-400 font-bold text-sm mb-2">QUICK START</h4>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm text-slate-400">
                  <div className="bg-slate-900 p-3 rounded border border-slate-800">
                    1. Download & Extract ZIP
                  </div>
                  <div className="bg-slate-900 p-3 rounded border border-slate-800">
                    2. Run <span className="font-mono text-white">npm install</span>
                  </div>
                  <div className="bg-slate-900 p-3 rounded border border-slate-800">
                    3. Run <span className="font-mono text-white">npm run dev</span>
                  </div>
                </div>
             </div>

             <div className="space-y-2">
               {plan.siteAssets && plan.siteAssets.length > 0 ? (
                 plan.siteAssets.map((file, idx) => (
                   <CodeBlock key={idx} file={file} />
                 ))
               ) : (
                 <div className="text-center p-10 text-slate-500">
                   No assets generated. Please run the analysis again.
                 </div>
               )}
             </div>
          </div>
        </div>
      )}
    </div>
  );
};
